=== ECF/JGroups/bundles/org.jgroups.mchannel/conf/jg-magic-map.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  A fully qualified Java class name 
  Used to dynamically load classes in the classpath
-->
<!ELEMENT class-name (#PCDATA)>

<!-- A free text description of an configuration element -->
<!ELEMENT description (#PCDATA)>

<!-- 
  Integer (java int) value for magic number to class mapping - 
  has to be unique within this file/one magic number per class
-->
<!ELEMENT magic-number (#PCDATA)>

<!--
  the preload element determines whether a class is preloaded or not 
  true means that the JGroups configurator will load the class upon parsing this file (pro-performance)
  false means that the class will not get loaded until used (pro-memory saving)
-->
<!ELEMENT preload (#PCDATA)>

<!-- 
  Initialization parameters for preloaded classes (Address, Header) 
  By default the Header and the Address base class have methods init(HashMap params)
  This method will get called with the values from the configuration file. This allows each individual
  class to have startup parameters
-->
<!ELEMENT init-param EMPTY>
<!ATTLIST init-param
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!-- 
  A list of initialization parameters
-->  
<!ELEMENT init-params (init-param+)>

<!-- 
  The definition of an address class.
  A class is defined by the class-name and the magic number. 
  The magic is number is unique, ie, within this file, a magic number can not 
  appear more than once.
  If that happens, the JGroups configurator will throw an exception upon parsing this file.
-->  
<!ELEMENT class (description, class-name, preload, magic-number, init-params?)>

<!-- 
      magic-number-class-mapping allows you to configure magic numbers for addresses and headers
      these classes can also be configured to be preloaded or not
-->
<!ELEMENT magic-number-class-mapping (class*)>

=== ECF/JGroups/bundles/org.jgroups.mchannel/conf/jg-magic-map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE jgroups-internal SYSTEM "jg-magic-map.dtd"> -->
<magic-number-class-mapping>
    <class>
        <description>IPv4 Address (4 bytes) + port</description>
        <class-name>org.jgroups.stack.IpAddress</class-name>
        <preload>true</preload>
        <magic-number>1</magic-number>
    </class>
    <class>
        <description>CAUSAL Header</description>
        <class-name>org.jgroups.protocols.CAUSAL$CausalHeader</class-name>
        <preload>true</preload>
        <magic-number>2</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.FD$FdHeader</class-name>
        <preload>true</preload>
        <magic-number>3</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.FD_SOCK$FdHeader</class-name>
        <preload>true</preload>
        <magic-number>6</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.FragHeader</class-name>
        <preload>true</preload>
        <magic-number>7</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.PingHeader</class-name>
        <preload>true</preload>
        <magic-number>13</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.TcpHeader</class-name>
        <preload>true</preload>
        <magic-number>14</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.TunnelHeader</class-name>
        <preload>true</preload>
        <magic-number>19</magic-number>
    </class>
    <class>
        <description>UDP Header</description>
        <class-name>org.jgroups.protocols.UdpHeader</class-name>
        <preload>true</preload>
        <magic-number>20</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.UNICAST$UnicastHeader</class-name>
        <preload>true</preload>
        <magic-number>21</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.VERIFY_SUSPECT$VerifyHeader</class-name>
        <preload>true</preload>
        <magic-number>22</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.pbcast.GMS$GmsHeader</class-name>
        <preload>true</preload>
        <magic-number>24</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.pbcast.NakAckHeader</class-name>
        <preload>true</preload>
        <magic-number>25</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.pbcast.STABLE$StableHeader</class-name>
        <preload>true</preload>
        <magic-number>27</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.pbcast.STATE_TRANSFER$StateHeader</class-name>
        <preload>true</preload>
        <magic-number>28</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.SMACK$SmackHeader</class-name>
        <preload>true</preload>
        <magic-number>29</magic-number>
    </class>
    <class>
        <description>Message</description>
        <class-name>org.jgroups.Message</class-name>
        <preload>true</preload>
        <magic-number>30</magic-number>
    </class>
    <class>
        <description>View</description>
        <class-name>org.jgroups.View</class-name>
        <preload>true</preload>
        <magic-number>31</magic-number>
    </class>
     <class>
        <description>ViewId</description>
        <class-name>org.jgroups.ViewId</class-name>
        <preload>true</preload>
        <magic-number>32</magic-number>
    </class>
    <class>
        <description>List</description>
        <class-name>org.jgroups.util.List</class-name>
        <preload>true</preload>
        <magic-number>33</magic-number>
    </class>
    <class>
        <description>Address</description>
        <class-name>org.jgroups.Address</class-name>
        <preload>true</preload>
        <magic-number>34</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.blocks.RequestCorrelator$Header</class-name>
        <preload>true</preload>
        <magic-number>35</magic-number>
    </class>
     <class>
        <description>PingRsp</description>
        <class-name>org.jgroups.protocols.PingRsp</class-name>
        <preload>true</preload>
        <magic-number>36</magic-number>
    </class>
     <class>
        <description>Vector</description>
        <class-name>java.util.Vector</class-name>
        <preload>true</preload>
        <magic-number>38</magic-number>
     </class>
    <class>
        <description>JoinRsp</description>
        <class-name>org.jgroups.protocols.pbcast.JoinRsp</class-name>
        <preload>true</preload>
        <magic-number>39</magic-number>
    </class>
    <class>
        <description>Digest</description>
        <class-name>org.jgroups.util.Digest</class-name>
        <preload>true</preload>
        <magic-number>40</magic-number>
    </class>
    <class>
        <description>Hashtable</description>
        <class-name>java.util.Hashtable</class-name>
        <preload>true</preload>
        <magic-number>41</magic-number>
    </class>
    <class>
        <description>Header for COMPRESS protocol</description>
        <class-name>org.jgroups.protocols.COMPRESS$CompressHeader</class-name>
        <preload>true</preload>
        <magic-number>53</magic-number>
    </class>
    <class>
        <description>Header for FC protocol</description>
        <class-name>org.jgroups.protocols.FC$FcHeader</class-name>
        <preload>true</preload>
        <magic-number>54</magic-number>
    </class>
    <class>
        <description>TP Header</description>
        <class-name>org.jgroups.protocols.TpHeader</class-name>
        <preload>true</preload>
        <magic-number>56</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.ENCRYPT$EncryptHeader</class-name>
        <preload>true</preload>
        <magic-number>57</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.SEQUENCER$SequencerHeader</class-name>
        <preload>true</preload>
        <magic-number>58</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.FD_SIMPLE$FdHeader</class-name>
        <preload>true</preload>
        <magic-number>59</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.VIEW_SYNC$ViewSyncHeader</class-name>
        <preload>true</preload>
        <magic-number>60</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.FD_ALL$Header</class-name>
        <preload>true</preload>
        <magic-number>61</magic-number>
    </class>
    <class>
        <description>(Description goes here)</description>
        <class-name>org.jgroups.protocols.SFC$Header</class-name>
        <preload>true</preload>
        <magic-number>62</magic-number>
    </class>

</magic-number-class-mapping>
